# Development specific values
ingress:
  enabled: true
  hosts:
    - host: genai-developmentv1.team-cache-me-if-you-can.student.k8s.aet.cit.tum.de
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: genai-dev-tls
     hosts:
       - genai-developmentv1.team-cache-me-if-you-can.student.k8s.aet.cit.tum.de

weaviate:
  persistence:
    enabled: false # Using emptyDir for development

# For development, we deploy redis as part of the chart
redis:
  enabled: true

monitoring:
  enabled: true
  grafana:
    adminPassword: "password" # insecure, for dev only 