apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-config
data:
  DB_URL: {{ .Values.env.DB_URL | quote }}
  DB_USERNAME: {{ .Values.env.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | quote }}
