apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.monitoring.loki.name }}-config
  labels:
    app: {{ .Values.monitoring.loki.name }}
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 1m
      chunk_target_size: 1048576
      chunk_retain_period: 30s
      max_transfer_retries: 0
    schema_config:
      configs:
        - from: "2020-10-24"
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.monitoring.loki.name }}
  labels:
    app: {{ .Values.monitoring.loki.name }}
spec:
  replicas: 1
  serviceName: {{ .Values.monitoring.loki.name }}
  selector:
    matchLabels:
      app: {{ .Values.monitoring.loki.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.monitoring.loki.name }}
    spec:
      containers:
        - name: loki
          image: {{ .Values.monitoring.loki.image }}
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
          ports:
            - containerPort: 3100
              name: http-metrics
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: {{ .Values.monitoring.loki.name }}-config
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.monitoring.loki.name }}
  labels:
    app: {{ .Values.monitoring.loki.name }}
spec:
  ports:
    - port: 3100
      name: http-metrics
  selector:
    app: {{ .Values.monitoring.loki.name }} 