apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: cache-me-if-you-can-genai  # Added namespace

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
