all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    development:
      hosts:
        localhost:
    pre_prod:
      hosts:
        localhost:
    prod:
      hosts:
        localhost: 