---
all:
  hosts:
    localhost:
      ansible_connection: local

ungrouped: {}

children:
  development:
    hosts:
      localhost:
  pre_prod:
    hosts:
      localhost:
  prod:
    hosts:
      localhost: 