apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-app
  namespace: dev
  labels:
    app: genai-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-app
  template:
    metadata:
      labels:
        app: genai-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: genai-app
        image: ghcr.io/aet-devops25/team-cache-me-if-you-can/genai-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: WEAVIATE_URL
          value: "http://weaviate-service.dev.svc.cluster.local:8080" # Assuming Weaviate service will be named 'weaviate-service' in the same namespace
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-credentials
              key: OPENAI_API_KEY