apiVersion: v1
kind: Service
metadata:
  name: genai-app-service
  namespace: cache-me-if-you-can-genai
spec:
  selector:
    app: genai-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP # Or LoadBalancer if you need external access directly via IP 