apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cache-me-if-you-can-genai-ingress
  namespace: cache-me-if-you-can-genai
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - cache-me-if-you-can-genai.student.k8s.aet.cit.tum.de
    secretName: cache-me-if-you-can-genai-tls
  rules:
  - host: cache-me-if-you-can-genai.student.k8s.aet.cit.tum.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: genai-app-service
            port:
              number: 8000