apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-celery-worker
  namespace: development
  labels:
    app: genai-celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-celery-worker
  template:
    metadata:
      labels:
        app: genai-celery-worker
    spec:
      containers:
      - name: genai-celery-worker
        image: ghcr.io/aet-devops25/team-cache-me-if-you-can/genai-app:latest
        command: ["celery", "-A", "app.celery_worker.celery_app", "worker", "--loglevel=info"]
        env:
        - name: CELERY_BROKER_URL
          value: "redis://redis:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis:6379/0"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-credentials
              key: OPENAI_API_KEY
        - name: WEAVIATE_URL
          value: "http://weaviate:8080" 