apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genai-chart.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "genai-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: genai-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "genai-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: genai-app
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "genai-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: genai-app
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "genai-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Values.genai_app.name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: WEAVIATE_URL
          value: "http://{{ .Release.Name }}-weaviate-service:8080"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.genai_app.env.OPENAI_API_KEY_SECRET_NAME }}
              key: OPENAI_API_KEY
        - name: CELERY_BROKER_URL
          value: {{ tpl .Values.genai_app.env.CELERY_BROKER_URL . | quote }}
        - name: CELERY_RESULT_BACKEND
          value: {{ tpl .Values.genai_app.env.CELERY_RESULT_BACKEND . | quote }}
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}