{{- if .Values.monitoring.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.monitoring.grafana.name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.monitoring.grafana.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.monitoring.grafana.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.monitoring.grafana.name }}
    spec:
      containers:
      - name: {{ .Values.monitoring.grafana.name }}
        image: {{ .Values.monitoring.grafana.image }}
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.monitoring.grafana.adminPassword | quote }}
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
{{- end }} 