{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.monitoring.loki.name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.monitoring.loki.name }}
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
{{- end }} 