name: Deploy Client with Terraform

on:
  push:
    branches:
      - workflow/move-client-to-new-namespace

jobs:
  terraform:
    name: Deploy Client with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up Kubernetes tools
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo '${{ secrets.KUBE_CONFIG_DATA }}' > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config use-context student
          kubectl config set-context --current --namespace=dev

      - name: Terraform Init
        run: terraform init
        working-directory: ./client/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./client/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./client/terraform
        env:
          KUBECONFIG: ~/.kube/config
