name: Genai CI/CD Pipeline

on:
  push:
    branches:
      - '**' # Runs on push to any branch
  pull_request:
    branches:
      - main # Runs on pull requests targeting main (for tests before merge)

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request' # Ensure it runs for both pushes and PRs

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # You can adjust this version

      - name: Install dependencies
        run: pip install -r genai/requirements.txt

      - name: Run tests
        run: pytest genai/tests

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: test # Ensure tests pass before deploying (only for pushes to main)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Only run on push to main

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        uses: azure/k8s-set-context@v4 # A common action to set up kubectl
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }} # IMPORTANT: You'll need to create this secret

      - name: Deploy to Kubernetes
        run: kubectl apply -f genai/k8s 