name: Python Lint

on:
  push:
    branches-ignore: []
    paths:
      - 'genai/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'genai/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Нужно для некоторых проверок, связанных с git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run linters
        run: |
          flake8 --max-line-length=200 genai
          black --check --line-length=200 genai